export {
  createPreSessionChallenge,
  normalizePrimaryEmail,
  type AuthenticatedCsrfDigest,
  type CheckSignInRateLimitInput,
  type ClearSignInRateLimitInput,
  type ConsumePreSessionChallengeInput,
  type CreatedPreSessionChallenge,
  type CreatePreSessionChallenge,
  type CreatePreSessionChallengeInput,
  type IssuedSession,
  type IssueSessionInput,
  type NormalizedEmail,
  type PasswordVerificationPort,
  type PasswordVerificationResult,
  type PreSessionChallengePort,
  type PreSessionCsrfDigest,
  type SessionCredentialDigest,
  type SessionIssuanceResult,
  type SessionIssuanceTransactionPort,
  type SignInRateLimitAccountKey,
  type SignInRateLimitDecision,
  type SignInRateLimitPort,
  type StorePreSessionChallengeInput,
  type RecordSignInRateLimitFailureInput,
  type VerifyPasswordInput,
} from './sign-in.js';
export {
  createInspectCurrentSession,
  type AnonymousSessionInspection,
  type AuthenticatedSessionInspection,
  type InspectCurrentSessionInput,
  type InspectCurrentSession,
  type ResolveSessionInput,
  type SessionLookupKey,
  type SessionResolutionPort,
  type SessionInspection,
} from './session-inspection.js';
export {
  FinancialRuleError,
  applyPayment,
  previewSale,
  simpleCashResult,
  type SaleFinancialPreview,
} from '@sem-caderno/domain';
export {
  MvpConflictError,
  MvpNotFoundError,
  MvpValidationError,
  type Activity,
  type BusinessSnapshot,
  type Customer,
  type Expense,
  type FinancialStatus,
  type MvpStore,
  type Payment,
  type Product,
  type PublicSession,
  type Sale,
  type SaleDraft,
  type SaleItem,
} from './mvp-model.js';
